### ISSUE TITLE
React-native-storybook with react-native-vector-icons and react-native-paper

### ISSUE THREAD

**Issue by Angelk90** [ugglr/react-native-storybook-boilerplate#8]
Hi @ugglr ,

I read your guide I wanted to congratulate you, but I had several problems during the configuration which in case I will deal with another issue later, so I downloaded your boilerplate and installed it, everything went well without problems in this case.

Let's move on to this issue, I am developing a component that uses `react-native-paper` which should also run on the  `web` as the documentation says.

In turn, `react-native-paper` uses `react-native-vector-icons`.

I am getting the following problem I don't understand what it comes from, if you look below where the error is indicated you see that the component is being rendered, so it seems that everything works weird the following two errors.

Could you give me a hand?

<img width="1224" alt="Schermata 2020-12-20 alle 13 01 22" src="https://user-images.githubusercontent.com/20476002/102712746-accb6980-42c3-11eb-8eda-f163ac53d965.png">

**Comment by ugglr** [comment]
The problem you are facing is not really in the scope for this project. You are getting this error because on the web, webpack does not know what to do with react native code, in my tutorial I used aliases to swap out any native import with something that can be displayed on the web directly. 

for instance: imports from react-native will instead import from react-native-web, or imports from styled-components/native will import from styled-components. 

what you want to do is to find a valid webpack config for react-native-vector-icons from someone who has it working on the web through react-native-web

react-native-paper has a doc for how to use on the web:
- https://callstack.github.io/react-native-paper/using-on-the-web.html

I think that's a good place to start.

here's another link that might help you find a solution:
- https://stackoverflow.com/questions/60263461/how-to-use-react-native-vector-icons-with-react-native-web

**Comment by ugglr** [comment]
As this issue is not in the scope of this project, and there's no active discussion, I'm closing.
